#!/bin/bash

function usage {
cat <<EOF
USAGE: $(basename $0) <eb|ek|xp> <board_serial> <factory_serial> <macAddr> <ipcfg>
  * eb             -- for dermalog embedded board
  * ek             -- for evaluation kit
  * xp             -- for explained board
  * board_serial   -- the serial number flashed to board like e.g. EB ZZ999999
  * faclory_serial -- the board serial generated by factory e.g. 99999999
  * macAddr        -- mac adresss for the board e.g. 0x001122334455 if not defined one will be generated
  * ipconfig       -- ip configuration in format "<ip-address>i/<netmask-bits> <gateway>" 
                      e.g. "10.120.13.88/24 10.120.23.254" 
                      if not defined dhcp wiil be selected
EOF
}

export DISPLAY=10.120.13.44:0.0

if  [[ -z ${1} ]]; then
    echo "please specify board"
    usage
    exit 1
fi

if [[ -z ${2} ]]; then
    echo "please specify board serial number"
    usage
    exit 2
fi

../sam-ba/sam-ba /dev/$(readlink /dev/ttySAMBA) AT91SAMA5D3x-EK flash.tcl "${1}" "${2}" "${3}" "${4}" "${5}"
#:> logfile.log 2>&1
#cat logfile.log
